name: Build and Publish Backstage Production image

on:
  push:
    branches:
      - main

jobs:
  build-test-publish:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker
      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2
    
      - name: Install dependencies and build Backstage
        run: |
          yarn install --frozen-lockfile && yarn tsc && yarn build:backend

      - name: Build Backstage Docker image
        run: |
          DOCKER_BUILDKIT=1 docker build -f packages/backend/Dockerfile --tag docker.theflyingbirds.net/backstage:latest \
            --build-arg POSTGRES_HOST="${{ secrets.POSTGRES_HOST }}" \
            --build-arg POSTGRES_PORT="${{ secrets.POSTGRES_PORT }}" \
            --build-arg POSTGRES_USER="${{ secrets.POSTGRES_USER }}" \
            --build-arg POSTGRES_PASSWORD="${{ secrets.POSTGRES_PASSWORD }}" \
            --build-arg AUTH_GITHUB_CLIENT_ID="${{ secrets.AUTH_GITHUB_CLIENT_ID }}" \
            --build-arg AUTH_GITHUB_CLIENT_SECRET="${{ secrets.AUTH_GITHUB_CLIENT_SECRET }}" \
            --build-arg TFB_APP_ID="${{ secrets.TFB_APP_ID }}" \
            --build-arg TFB_APP_WEBHOOKURL="${{ secrets.TFB_APP_WEBHOOKURL }}" \
            --build-arg TFB_APP_CLIENT_ID="${{ secrets.TFB_APP_CLIENT_ID }}" \
            --build-arg TFB_APP_CLIENT_SECRET="${{ secrets.TFB_APP_CLIENT_SECRET }}" \
            --build-arg TFB_APP_WEBHOOK_SECRET="${{ secrets.TFB_APP_WEBHOOK_SECRET }}" \
            --build-arg TFB_APP_PRIVATE_KEY_0="${{ secrets.TFB_APP_PRIVATE_KEY_0 }}" \
            --build-arg TFB_APP_PRIVATE_KEY_1="${{ secrets.TFB_APP_PRIVATE_KEY_1 }}" \
            --build-arg TFB_APP_PRIVATE_KEY_2="${{ secrets.TFB_APP_PRIVATE_KEY_2 }}" \
            --build-arg TFB_APP_PRIVATE_KEY_3="${{ secrets.TFB_APP_PRIVATE_KEY_3 }}" \
            --build-arg TFB_APP_PRIVATE_KEY_4="${{ secrets.TFB_APP_PRIVATE_KEY_4 }}" \
            --build-arg TFB_APP_PRIVATE_KEY_5="${{ secrets.TFB_APP_PRIVATE_KEY_5 }}" \
            --build-arg TFB_APP_PRIVATE_KEY_6="${{ secrets.TFB_APP_PRIVATE_KEY_6 }}" \
            --build-arg TFB_APP_PRIVATE_KEY_7="${{ secrets.TFB_APP_PRIVATE_KEY_7 }}" \
            --build-arg TFB_APP_PRIVATE_KEY_8="${{ secrets.TFB_APP_PRIVATE_KEY_8 }}" \
            --build-arg TFB_APP_PRIVATE_KEY_9="${{ secrets.TFB_APP_PRIVATE_KEY_9 }}" \
            --build-arg TFB_APP_PRIVATE_KEY_10="${{ secrets.TFB_APP_PRIVATE_KEY_10 }}" \
            --build-arg TFB_APP_PRIVATE_KEY_11="${{ secrets.TFB_APP_PRIVATE_KEY_11 }}" \
            --build-arg TFB_APP_PRIVATE_KEY_12="${{ secrets.TFB_APP_PRIVATE_KEY_12 }}" \
            --build-arg TFB_APP_PRIVATE_KEY_13="${{ secrets.TFB_APP_PRIVATE_KEY_13 }}" \
            --build-arg TFB_APP_PRIVATE_KEY_14="${{ secrets.TFB_APP_PRIVATE_KEY_14 }}" \
            --build-arg TFB_APP_PRIVATE_KEY_15="${{ secrets.TFB_APP_PRIVATE_KEY_15 }}" \
            --build-arg TFB_APP_PRIVATE_KEY_16="${{ secrets.TFB_APP_PRIVATE_KEY_16 }}" \
            --build-arg TFB_APP_PRIVATE_KEY_17="${{ secrets.TFB_APP_PRIVATE_KEY_17 }}" \
            --build-arg TFB_APP_PRIVATE_KEY_18="${{ secrets.TFB_APP_PRIVATE_KEY_18 }}" \
            --build-arg TFB_APP_PRIVATE_KEY_19="${{ secrets.TFB_APP_PRIVATE_KEY_19 }}" \
            --build-arg TFB_APP_PRIVATE_KEY_20="${{ secrets.TFB_APP_PRIVATE_KEY_20 }}" \
            --build-arg TFB_APP_PRIVATE_KEY_21="${{ secrets.TFB_APP_PRIVATE_KEY_21 }}" \
            --build-arg TFB_APP_PRIVATE_KEY_22="${{ secrets.TFB_APP_PRIVATE_KEY_22 }}" \
            --build-arg TFB_APP_PRIVATE_KEY_23="${{ secrets.TFB_APP_PRIVATE_KEY_23 }}" \
            --build-arg TFB_APP_PRIVATE_KEY_24="${{ secrets.TFB_APP_PRIVATE_KEY_24 }}" \
            .

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.MAVEN_USERNAME }}
          password: ${{ secrets.MAVEN_PASSWORD }}
      - name: Push
        run: docker push ${{ secrets.DOCKER_REGISTRY }}/backstage:latest

      # Login to Nexus Artifactory
      # - name: Login to Nexus Docker Registry
      #   uses: docker/login-action@v2
      #   with:
      #     registry: ${{ secrets.MAVEN_DOCKER_REPO }} # change this to your Nexus Registry URL
      #     username: ${{ secrets.MAVEN_USERNAME }}
      #     password: ${{ secrets.MAVEN_PASSWORD }}

      # # Build and push Docker image
      # - name: Build and push Docker image
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: ./packages/backend # specifying the directory where your Dockerfile is
      #     file: ./packages/backend/Dockerfile # specifying the path to your Dockerfile
      #     push: true
      #     tags: ${{ secrets.MAVEN_DOCKER_REPO }}/backstage:latest # change this to your image name
